[2024-06-14T09:23:46.854+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spark_dag.spark_query_csv manual__2024-06-14T09:23:43.593436+00:00 [queued]>
[2024-06-14T09:23:46.863+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spark_dag.spark_query_csv manual__2024-06-14T09:23:43.593436+00:00 [queued]>
[2024-06-14T09:23:46.864+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-14T09:23:46.875+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): spark_query_csv> on 2024-06-14 09:23:43.593436+00:00
[2024-06-14T09:23:46.885+0000] {standard_task_runner.py:57} INFO - Started process 4162 to run task
[2024-06-14T09:23:46.915+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Spark_dag', 'spark_query_csv', 'manual__2024-06-14T09:23:43.593436+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/Spark_dag.py', '--cfg-path', '/tmp/tmpb0i0luf8']
[2024-06-14T09:23:46.919+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask spark_query_csv
[2024-06-14T09:23:47.021+0000] {task_command.py:415} INFO - Running <TaskInstance: Spark_dag.spark_query_csv manual__2024-06-14T09:23:43.593436+00:00 [running]> on host 963b3fbfa4c9
[2024-06-14T09:23:47.154+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Spark_dag' AIRFLOW_CTX_TASK_ID='spark_query_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T09:23:43.593436+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T09:23:43.593436+00:00'
[2024-06-14T09:23:47.176+0000] {base.py:73} INFO - Using connection ID 'Spark_connection' for task execution.
[2024-06-14T09:23:47.179+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://host.docker.internal:9000 --conf spark.hadoop.fs.s3a.access.key=fPMHZA3ZV0g2so9iydgd --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --name arrow-spark --deploy-mode client /opt/bitnami/spark/jobs/python/pyspark_test.py s3a://data-lake/allstockprice.csv fPMHZA3ZV0g2so9iydgd 2wY04v8tSwkpVb054WFro0AP6SJ4mjvHbVHurSUp
[2024-06-14T09:23:47.350+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-14T09:23:49.912+0000] {spark_submit.py:571} INFO - python3: can't open file '/opt/bitnami/spark/jobs/python/pyspark_test.py': [Errno 2] No such file or directory
[2024-06-14T09:23:49.933+0000] {spark_submit.py:571} INFO - 24/06/14 09:23:49 INFO ShutdownHookManager: Shutdown hook called
[2024-06-14T09:23:49.935+0000] {spark_submit.py:571} INFO - 24/06/14 09:23:49 INFO ShutdownHookManager: Deleting directory /tmp/spark-4c72d809-ac1b-4bdf-9873-a3f6e39c50c5
[2024-06-14T09:23:49.995+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://host.docker.internal:9000 --conf spark.hadoop.fs.s3a.access.key=fPMHZA3ZV0g2so9iydgd --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --name arrow-spark --deploy-mode client /opt/bitnami/spark/jobs/python/pyspark_test.py s3a://data-lake/allstockprice.csv fPMHZA3ZV0g2so9iydgd 2wY04v8tSwkpVb054WFro0AP6SJ4mjvHbVHurSUp. Error code is: 2.
[2024-06-14T09:23:50.008+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Spark_dag, task_id=spark_query_csv, execution_date=20240614T092343, start_date=20240614T092346, end_date=20240614T092350
[2024-06-14T09:23:50.027+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 50 for task spark_query_csv (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://host.docker.internal:9000 --conf spark.hadoop.fs.s3a.access.key=fPMHZA3ZV0g2so9iydgd --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --name arrow-spark --deploy-mode client /opt/bitnami/spark/jobs/python/pyspark_test.py s3a://data-lake/allstockprice.csv fPMHZA3ZV0g2so9iydgd 2wY04v8tSwkpVb054WFro0AP6SJ4mjvHbVHurSUp. Error code is: 2.; 4162)
[2024-06-14T09:23:50.073+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-14T09:23:50.126+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
