[2024-06-14T11:20:30.087+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_minio_example.spark_submit_task scheduled__2024-06-13T11:20:24.097595+00:00 [queued]>
[2024-06-14T11:20:30.094+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_minio_example.spark_submit_task scheduled__2024-06-13T11:20:24.097595+00:00 [queued]>
[2024-06-14T11:20:30.097+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-06-14T11:20:30.112+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2024-06-13 11:20:24.097595+00:00
[2024-06-14T11:20:30.120+0000] {standard_task_runner.py:57} INFO - Started process 7489 to run task
[2024-06-14T11:20:30.123+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_minio_example', 'spark_submit_task', 'scheduled__2024-06-13T11:20:24.097595+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/simple_spark_dag.py', '--cfg-path', '/tmp/tmp2oj15iho']
[2024-06-14T11:20:30.126+0000] {standard_task_runner.py:85} INFO - Job 58: Subtask spark_submit_task
[2024-06-14T11:20:30.166+0000] {task_command.py:415} INFO - Running <TaskInstance: spark_minio_example.spark_submit_task scheduled__2024-06-13T11:20:24.097595+00:00 [running]> on host 963b3fbfa4c9
[2024-06-14T11:20:30.221+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_minio_example' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T11:20:24.097595+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T11:20:24.097595+00:00'
[2024-06-14T11:20:30.229+0000] {base.py:73} INFO - Using connection ID 'Spark_connection' for task execution.
[2024-06-14T11:20:30.230+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=khaiVDT2024 --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --name spark_minio_job --deploy-mode client /jobs/python/test2
[2024-06-14T11:20:30.651+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-14T11:20:43.886+0000] {spark_submit.py:571} INFO - 24/06/14 11:20:43 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-06-14T11:20:44.725+0000] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: Failed to get main class in JAR with error 'File file:/jobs/python/test2 does not exist'.  Please specify one with --class.
[2024-06-14T11:20:44.734+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.error(SparkSubmit.scala:1038)
[2024-06-14T11:20:44.744+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:524)
[2024-06-14T11:20:44.750+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
[2024-06-14T11:20:44.754+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:192)
[2024-06-14T11:20:44.761+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:215)
[2024-06-14T11:20:44.764+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2024-06-14T11:20:44.769+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1111)
[2024-06-14T11:20:44.775+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1120)
[2024-06-14T11:20:44.780+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-06-14T11:20:45.170+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=khaiVDT2024 --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --name spark_minio_job --deploy-mode client /jobs/python/test2. Error code is: 1.
[2024-06-14T11:20:45.197+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=spark_minio_example, task_id=spark_submit_task, execution_date=20240613T112024, start_date=20240614T112030, end_date=20240614T112045
[2024-06-14T11:20:45.241+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 58 for task spark_submit_task (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=khaiVDT2024 --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --name spark_minio_job --deploy-mode client /jobs/python/test2. Error code is: 1.; 7489)
[2024-06-14T11:20:45.302+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-14T11:20:45.395+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
