[2024-06-13T17:32:37.694+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T17:32:37.713+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_upload_dag.query_job manual__2024-06-13T17:30:35.650285+00:00 [queued]>
[2024-06-13T17:32:37.719+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_upload_dag.query_job manual__2024-06-13T17:30:35.650285+00:00 [queued]>
[2024-06-13T17:32:37.723+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-13T17:32:37.739+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): query_job> on 2024-06-13 17:30:35.650285+00:00
[2024-06-13T17:32:37.756+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_upload_dag', 'query_job', 'manual__2024-06-13T17:30:35.650285+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/Upload_minio.py', '--cfg-path', '/tmp/tmp_i8aroxd']
[2024-06-13T17:32:37.760+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=751) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-13T17:32:37.762+0000] {standard_task_runner.py:91} INFO - Job 137: Subtask query_job
[2024-06-13T17:32:37.762+0000] {standard_task_runner.py:63} INFO - Started process 755 to run task
[2024-06-13T17:32:37.914+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_upload_dag.query_job manual__2024-06-13T17:30:35.650285+00:00 [running]> on host 18e56691db61
[2024-06-13T17:32:38.086+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_upload_dag' AIRFLOW_CTX_TASK_ID='query_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T17:30:35.650285+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T17:30:35.650285+00:00'
[2024-06-13T17:32:38.097+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T17:32:38.175+0000] {spark_submit.py:271} INFO - Could not load connection string spark-conn, defaulting to yarn
[2024-06-13T17:32:38.179+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --packages org.apache.hudi:hudi-spark3.4-bundle_2.12:0.14.0,org.apache.hadoop:hadoop-aws:3.3.2 --name arrow-spark jobs/python/hudi_spark_minio.py
[2024-06-13T17:32:38.379+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-13T17:32:38.434+0000] {spark_submit.py:571} INFO - JAVA_HOME is not set
[2024-06-13T17:32:38.445+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T17:32:38.456+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --packages org.apache.hudi:hudi-spark3.4-bundle_2.12:0.14.0,org.apache.hadoop:hadoop-aws:3.3.2 --name arrow-spark jobs/python/hudi_spark_minio.py. Error code is: 1.
[2024-06-13T17:32:38.469+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=minio_upload_dag, task_id=query_job, run_id=manual__2024-06-13T17:30:35.650285+00:00, execution_date=20240613T173035, start_date=20240613T173237, end_date=20240613T173238
[2024-06-13T17:32:38.487+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 137 for task query_job (Cannot execute: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --packages org.apache.hudi:hudi-spark3.4-bundle_2.12:0.14.0,org.apache.hadoop:hadoop-aws:3.3.2 --name arrow-spark jobs/python/hudi_spark_minio.py. Error code is: 1.; 755)
[2024-06-13T17:32:38.494+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-13T17:32:38.525+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T17:32:38.544+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
