[2024-06-14T08:52:10.974+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spark_dag.spark_query_csv manual__2024-06-14T08:52:08.946828+00:00 [queued]>
[2024-06-14T08:52:10.979+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spark_dag.spark_query_csv manual__2024-06-14T08:52:08.946828+00:00 [queued]>
[2024-06-14T08:52:10.980+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-14T08:52:10.989+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): spark_query_csv> on 2024-06-14 08:52:08.946828+00:00
[2024-06-14T08:52:11.003+0000] {standard_task_runner.py:57} INFO - Started process 2893 to run task
[2024-06-14T08:52:11.012+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Spark_dag', 'spark_query_csv', 'manual__2024-06-14T08:52:08.946828+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/Spark_dag.py', '--cfg-path', '/tmp/tmpmsjzrg_w']
[2024-06-14T08:52:11.018+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask spark_query_csv
[2024-06-14T08:52:11.097+0000] {task_command.py:415} INFO - Running <TaskInstance: Spark_dag.spark_query_csv manual__2024-06-14T08:52:08.946828+00:00 [running]> on host 963b3fbfa4c9
[2024-06-14T08:52:11.178+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Spark_dag' AIRFLOW_CTX_TASK_ID='spark_query_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T08:52:08.946828+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T08:52:08.946828+00:00'
[2024-06-14T08:52:11.191+0000] {base.py:73} INFO - Using connection ID 'Spark_connection' for task execution.
[2024-06-14T08:52:11.192+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=fPMHZA3ZV0g2so9iydgd --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --name minio_csv_query --deploy-mode client jobs/python/query_spark.py s3a://data-lake/allstockprice.csv fPMHZA3ZV0g2so9iydgd 2wY04v8tSwkpVb054WFro0AP6SJ4mjvHbVHurSUp
[2024-06-14T08:52:11.365+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-14T08:52:13.812+0000] {spark_submit.py:571} INFO - python3: can't open file '/opt/***/jobs/python/query_spark.py': [Errno 2] No such file or directory
[2024-06-14T08:52:13.832+0000] {spark_submit.py:571} INFO - 24/06/14 08:52:13 INFO ShutdownHookManager: Shutdown hook called
[2024-06-14T08:52:13.834+0000] {spark_submit.py:571} INFO - 24/06/14 08:52:13 INFO ShutdownHookManager: Deleting directory /tmp/spark-18d06186-64c2-4cc8-9c7f-89bc7500904f
[2024-06-14T08:52:13.901+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=fPMHZA3ZV0g2so9iydgd --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --name minio_csv_query --deploy-mode client jobs/python/query_spark.py s3a://data-lake/allstockprice.csv fPMHZA3ZV0g2so9iydgd 2wY04v8tSwkpVb054WFro0AP6SJ4mjvHbVHurSUp. Error code is: 2.
[2024-06-14T08:52:13.907+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Spark_dag, task_id=spark_query_csv, execution_date=20240614T085208, start_date=20240614T085210, end_date=20240614T085213
[2024-06-14T08:52:13.926+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task spark_query_csv (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=fPMHZA3ZV0g2so9iydgd --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --name minio_csv_query --deploy-mode client jobs/python/query_spark.py s3a://data-lake/allstockprice.csv fPMHZA3ZV0g2so9iydgd 2wY04v8tSwkpVb054WFro0AP6SJ4mjvHbVHurSUp. Error code is: 2.; 2893)
[2024-06-14T08:52:13.949+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-14T08:52:13.987+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
