[2024-06-13T20:02:48.472+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T20:02:48.488+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spark_dag.query_job manual__2024-06-13T20:02:42.148584+00:00 [queued]>
[2024-06-13T20:02:48.495+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spark_dag.query_job manual__2024-06-13T20:02:42.148584+00:00 [queued]>
[2024-06-13T20:02:48.496+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-13T20:02:48.520+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): query_job> on 2024-06-13 20:02:42.148584+00:00
[2024-06-13T20:02:48.535+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Spark_dag', 'query_job', 'manual__2024-06-13T20:02:42.148584+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/Spark_dag.py', '--cfg-path', '/tmp/tmp1l460ag3']
[2024-06-13T20:02:48.538+0000] {standard_task_runner.py:91} INFO - Job 157: Subtask query_job
[2024-06-13T20:02:48.539+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=484) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-13T20:02:48.541+0000] {standard_task_runner.py:63} INFO - Started process 490 to run task
[2024-06-13T20:02:48.584+0000] {task_command.py:426} INFO - Running <TaskInstance: Spark_dag.query_job manual__2024-06-13T20:02:42.148584+00:00 [running]> on host fba111c28c36
[2024-06-13T20:02:48.658+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Spark_dag' AIRFLOW_CTX_TASK_ID='query_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T20:02:42.148584+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T20:02:42.148584+00:00'
[2024-06-13T20:02:48.664+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T20:02:48.691+0000] {base.py:84} INFO - Using connection ID 'Spark_connection' for task execution.
[2024-06-13T20:02:48.693+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark --deploy-mode client jobs/python/pyspark_test.py
[2024-06-13T20:02:50.377+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-13T20:02:50.387+0000] {spark_submit.py:571} INFO - JAVA_HOME is not set
[2024-06-13T20:02:50.393+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T20:02:50.461+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark --deploy-mode client jobs/python/pyspark_test.py. Error code is: 1.
[2024-06-13T20:02:50.583+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Spark_dag, task_id=query_job, run_id=manual__2024-06-13T20:02:42.148584+00:00, execution_date=20240613T200242, start_date=20240613T200248, end_date=20240613T200250
[2024-06-13T20:02:50.674+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 157 for task query_job (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark --deploy-mode client jobs/python/pyspark_test.py. Error code is: 1.; 490)
[2024-06-13T20:02:50.756+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-13T20:02:50.819+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T20:02:51.019+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
