[2024-06-13T17:52:44.698+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T17:52:44.713+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spark_dag.query_job manual__2024-06-13T17:52:43.689701+00:00 [queued]>
[2024-06-13T17:52:44.719+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spark_dag.query_job manual__2024-06-13T17:52:43.689701+00:00 [queued]>
[2024-06-13T17:52:44.721+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-13T17:52:44.729+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): query_job> on 2024-06-13 17:52:43.689701+00:00
[2024-06-13T17:52:44.738+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Spark_dag', 'query_job', 'manual__2024-06-13T17:52:43.689701+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/Spark_dag.py', '--cfg-path', '/tmp/tmpyr2wfx_n']
[2024-06-13T17:52:44.740+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=329) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-13T17:52:44.742+0000] {standard_task_runner.py:91} INFO - Job 146: Subtask query_job
[2024-06-13T17:52:44.743+0000] {standard_task_runner.py:63} INFO - Started process 330 to run task
[2024-06-13T17:52:44.789+0000] {task_command.py:426} INFO - Running <TaskInstance: Spark_dag.query_job manual__2024-06-13T17:52:43.689701+00:00 [running]> on host 18e56691db61
[2024-06-13T17:52:44.860+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Spark_dag' AIRFLOW_CTX_TASK_ID='query_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T17:52:43.689701+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T17:52:43.689701+00:00'
[2024-06-13T17:52:44.862+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T17:52:44.889+0000] {spark_submit.py:271} INFO - Could not load connection string Spark-connection, defaulting to yarn
[2024-06-13T17:52:44.891+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark jobs/python/pyspark_test.py
[2024-06-13T17:52:44.947+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-13T17:52:44.950+0000] {spark_submit.py:571} INFO - JAVA_HOME is not set
[2024-06-13T17:52:44.951+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T17:52:44.957+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark jobs/python/pyspark_test.py. Error code is: 1.
[2024-06-13T17:52:44.961+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Spark_dag, task_id=query_job, run_id=manual__2024-06-13T17:52:43.689701+00:00, execution_date=20240613T175243, start_date=20240613T175244, end_date=20240613T175244
[2024-06-13T17:52:44.967+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 146 for task query_job (Cannot execute: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark jobs/python/pyspark_test.py. Error code is: 1.; 330)
[2024-06-13T17:52:45.012+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-13T17:52:45.023+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T17:52:45.025+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
