[2024-06-14T06:16:13.040+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T06:16:13.054+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spark_dag.query_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T06:16:13.061+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spark_dag.query_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T06:16:13.062+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-14T06:16:13.072+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): query_job> on 2024-06-13 00:00:00+00:00
[2024-06-14T06:16:13.086+0000] {standard_task_runner.py:63} INFO - Started process 209 to run task
[2024-06-14T06:16:13.091+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Spark_dag', 'query_job', 'scheduled__2024-06-13T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/Spark_dag.py', '--cfg-path', '/tmp/tmpgjy7ctx2']
[2024-06-14T06:16:13.098+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask query_job
[2024-06-14T06:16:13.173+0000] {task_command.py:426} INFO - Running <TaskInstance: Spark_dag.query_job scheduled__2024-06-13T00:00:00+00:00 [running]> on host c099674506c1
[2024-06-14T06:16:13.249+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Spark_dag' AIRFLOW_CTX_TASK_ID='query_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T00:00:00+00:00'
[2024-06-14T06:16:13.251+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T06:16:13.292+0000] {spark_submit.py:271} INFO - Could not load connection string Spark_connection, defaulting to yarn
[2024-06-14T06:16:13.295+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark jobs/python/pyspark_test.py
[2024-06-14T06:16:13.382+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-14T06:16:13.384+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-arm64/bin/java: No such file or directory
[2024-06-14T06:16:13.386+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2024-06-14T06:16:13.388+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T06:16:13.397+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark jobs/python/pyspark_test.py. Error code is: 1.
[2024-06-14T06:16:13.402+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Spark_dag, task_id=query_job, run_id=scheduled__2024-06-13T00:00:00+00:00, execution_date=20240613T000000, start_date=20240614T061613, end_date=20240614T061613
[2024-06-14T06:16:13.409+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task query_job (Cannot execute: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark jobs/python/pyspark_test.py. Error code is: 1.; 209)
[2024-06-14T06:16:13.438+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T06:16:13.450+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T06:16:13.452+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-14T06:42:16.349+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T06:42:16.436+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spark_dag.query_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T06:42:16.453+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spark_dag.query_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T06:42:16.456+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-14T06:42:16.526+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): query_job> on 2024-06-13 00:00:00+00:00
[2024-06-14T06:42:16.630+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Spark_dag', 'query_job', 'scheduled__2024-06-13T00:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/Spark_dag.py', '--cfg-path', '/tmp/tmplazowk_0']
[2024-06-14T06:42:16.671+0000] {standard_task_runner.py:91} INFO - Job 161: Subtask query_job
[2024-06-14T06:42:16.718+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=180) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-14T06:42:16.728+0000] {standard_task_runner.py:63} INFO - Started process 181 to run task
[2024-06-14T06:42:16.966+0000] {task_command.py:426} INFO - Running <TaskInstance: Spark_dag.query_job scheduled__2024-06-13T00:00:00+00:00 [running]> on host 3ebf863eace4
[2024-06-14T06:42:17.477+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Spark_dag' AIRFLOW_CTX_TASK_ID='query_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T00:00:00+00:00'
[2024-06-14T06:42:17.506+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T06:42:17.875+0000] {base.py:84} INFO - Using connection ID 'Spark_connection' for task execution.
[2024-06-14T06:42:17.886+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark --deploy-mode client jobs/python/pyspark_test.py
[2024-06-14T06:42:18.137+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-14T06:42:18.149+0000] {spark_submit.py:571} INFO - JAVA_HOME is not set
[2024-06-14T06:42:18.172+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T06:42:18.287+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark --deploy-mode client jobs/python/pyspark_test.py. Error code is: 1.
[2024-06-14T06:42:18.310+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Spark_dag, task_id=query_job, run_id=scheduled__2024-06-13T00:00:00+00:00, execution_date=20240613T000000, start_date=20240614T064216, end_date=20240614T064218
[2024-06-14T06:42:18.333+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 161 for task query_job (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark --deploy-mode client jobs/python/pyspark_test.py. Error code is: 1.; 181)
[2024-06-14T06:42:18.361+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T06:42:18.443+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T06:42:18.449+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-14T07:27:10.115+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spark_dag.query_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T07:27:10.121+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spark_dag.query_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T07:27:10.121+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-14T07:27:10.129+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): query_job> on 2024-06-13 00:00:00+00:00
[2024-06-14T07:27:10.133+0000] {standard_task_runner.py:57} INFO - Started process 192 to run task
[2024-06-14T07:27:10.138+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Spark_dag', 'query_job', 'scheduled__2024-06-13T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/Spark_dag.py', '--cfg-path', '/tmp/tmpje6jsy7x']
[2024-06-14T07:27:10.141+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask query_job
[2024-06-14T07:27:10.184+0000] {task_command.py:415} INFO - Running <TaskInstance: Spark_dag.query_job scheduled__2024-06-13T00:00:00+00:00 [running]> on host 28209c95e1f8
[2024-06-14T07:27:10.240+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Spark_dag' AIRFLOW_CTX_TASK_ID='query_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T00:00:00+00:00'
[2024-06-14T07:27:10.249+0000] {spark_submit.py:271} INFO - Could not load connection string Spark_connection, defaulting to yarn
[2024-06-14T07:27:10.250+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark jobs/python/pyspark_test.py
[2024-06-14T07:27:10.370+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-14T07:27:12.376+0000] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-06-14T07:27:12.380+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-06-14T07:27:12.381+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-06-14T07:27:12.382+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-06-14T07:27:12.383+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-06-14T07:27:12.384+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2024-06-14T07:27:12.385+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2024-06-14T07:27:12.385+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-06-14T07:27:12.386+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-06-14T07:27:12.387+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-06-14T07:27:12.388+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-06-14T07:27:12.411+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark jobs/python/pyspark_test.py. Error code is: 1.
[2024-06-14T07:27:12.420+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Spark_dag, task_id=query_job, execution_date=20240613T000000, start_date=20240614T072710, end_date=20240614T072712
[2024-06-14T07:27:12.438+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 36 for task query_job (Cannot execute: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark jobs/python/pyspark_test.py. Error code is: 1.; 192)
[2024-06-14T07:27:12.459+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-14T07:27:12.485+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T07:50:35.972+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spark_dag.query_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T07:50:35.982+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spark_dag.query_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T07:50:35.983+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-14T07:50:35.997+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): query_job> on 2024-06-13 00:00:00+00:00
[2024-06-14T07:50:36.011+0000] {standard_task_runner.py:57} INFO - Started process 231 to run task
[2024-06-14T07:50:36.026+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Spark_dag', 'query_job', 'scheduled__2024-06-13T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/Spark_dag.py', '--cfg-path', '/tmp/tmpj7gbtned']
[2024-06-14T07:50:36.039+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask query_job
[2024-06-14T07:50:36.144+0000] {task_command.py:415} INFO - Running <TaskInstance: Spark_dag.query_job scheduled__2024-06-13T00:00:00+00:00 [running]> on host 963b3fbfa4c9
[2024-06-14T07:50:36.250+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Spark_dag' AIRFLOW_CTX_TASK_ID='query_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T00:00:00+00:00'
[2024-06-14T07:50:36.267+0000] {spark_submit.py:271} INFO - Could not load connection string Spark_connection, defaulting to yarn
[2024-06-14T07:50:36.269+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark jobs/python/pyspark_test.py
[2024-06-14T07:50:36.459+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-14T07:50:42.348+0000] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-06-14T07:50:42.376+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-06-14T07:50:42.381+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-06-14T07:50:42.382+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-06-14T07:50:42.385+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-06-14T07:50:42.389+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1094)
[2024-06-14T07:50:42.396+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1094)
[2024-06-14T07:50:42.399+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-06-14T07:50:42.400+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1111)
[2024-06-14T07:50:42.402+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1120)
[2024-06-14T07:50:42.403+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-06-14T07:50:42.453+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark jobs/python/pyspark_test.py. Error code is: 1.
[2024-06-14T07:50:42.478+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Spark_dag, task_id=query_job, execution_date=20240613T000000, start_date=20240614T075035, end_date=20240614T075042
[2024-06-14T07:50:42.522+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task query_job (Cannot execute: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.instances=1 --name arrow-spark jobs/python/pyspark_test.py. Error code is: 1.; 231)
[2024-06-14T07:50:42.575+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-14T07:50:42.652+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
