[2024-06-14T06:42:22.053+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T06:42:22.129+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_upload_dag.crawl_data_task scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T06:42:22.208+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_upload_dag.crawl_data_task scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T06:42:22.250+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-14T06:42:22.260+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crawl_data_task> on 2024-06-13 00:00:00+00:00
[2024-06-14T06:42:22.270+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_upload_dag', 'crawl_data_task', 'scheduled__2024-06-13T00:00:00+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/Upload_minio.py', '--cfg-path', '/tmp/tmpr8veayh3']
[2024-06-14T06:42:22.273+0000] {standard_task_runner.py:91} INFO - Job 162: Subtask crawl_data_task
[2024-06-14T06:42:22.275+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=191) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-14T06:42:22.313+0000] {standard_task_runner.py:63} INFO - Started process 193 to run task
[2024-06-14T06:42:22.488+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_upload_dag.crawl_data_task scheduled__2024-06-13T00:00:00+00:00 [running]> on host 3ebf863eace4
[2024-06-14T06:42:22.674+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_upload_dag' AIRFLOW_CTX_TASK_ID='crawl_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T00:00:00+00:00'
[2024-06-14T06:42:22.709+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T06:46:30.147+0000] {logging_mixin.py:188} INFO - Error in API response {"status":500,"code":"INTERNAL_SERVER_ERROR","message":"internal server error, please try again later"}
[2024-06-14T06:46:30.214+0000] {logging_mixin.py:188} INFO -  
[2024-06-14T06:46:30.230+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T06:46:30.302+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Upload_minio.py", line 33, in crawl_data
    CrawlData.get_full_list_stock_price()
  File "/opt/airflow/code/CrawlData.py", line 31, in get_full_list_stock_price
    temp_df=pd.DataFrame(stock_historical_data(symbol=company, start_date=current_day(), end_date=current_day(), resolution="1D", type="stock", beautify=True, decor=False, source='DNSE'))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/vnstock/technical.py", line 24, in stock_historical_data
    df = ohlc_data(symbol, start_date, end_date, resolution, type, headers=entrade_headers)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/vnstock/technical.py", line 191, in ohlc_data
    return df
           ^^
UnboundLocalError: cannot access local variable 'df' where it is not associated with a value
[2024-06-14T06:46:30.743+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=minio_upload_dag, task_id=crawl_data_task, run_id=scheduled__2024-06-13T00:00:00+00:00, execution_date=20240613T000000, start_date=20240614T064222, end_date=20240614T064630
[2024-06-14T06:46:30.924+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 162 for task crawl_data_task (cannot access local variable 'df' where it is not associated with a value; 193)
[2024-06-14T06:46:31.117+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T06:46:31.579+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T06:46:31.625+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-14T07:37:27.511+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_upload_dag.crawl_data_task scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T07:37:27.520+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_upload_dag.crawl_data_task scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T07:37:27.521+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-14T07:37:27.534+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): crawl_data_task> on 2024-06-13 00:00:00+00:00
[2024-06-14T07:37:27.540+0000] {standard_task_runner.py:57} INFO - Started process 952 to run task
[2024-06-14T07:37:27.543+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'minio_upload_dag', 'crawl_data_task', 'scheduled__2024-06-13T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/Upload_minio.py', '--cfg-path', '/tmp/tmpwmomm4aa']
[2024-06-14T07:37:27.547+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask crawl_data_task
[2024-06-14T07:37:27.614+0000] {task_command.py:415} INFO - Running <TaskInstance: minio_upload_dag.crawl_data_task scheduled__2024-06-13T00:00:00+00:00 [running]> on host 28209c95e1f8
[2024-06-14T07:37:27.695+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_upload_dag' AIRFLOW_CTX_TASK_ID='crawl_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T00:00:00+00:00'
[2024-06-14T07:41:58.083+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2024-06-14T07:41:58.141+0000] {process_utils.py:131} INFO - Sending 15 to group 952. PIDs of all processes in the group: [952]
[2024-06-14T07:41:58.146+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 952
[2024-06-14T07:41:58.155+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-14T07:41:58.252+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Upload_minio.py", line 33, in crawl_data
    CrawlData.get_full_list_stock_price()
  File "/opt/airflow/code/CrawlData.py", line 31, in get_full_list_stock_price
    temp_df=pd.DataFrame(stock_historical_data(symbol=company, start_date=current_day(), end_date=current_day(), resolution="1D", type="stock", beautify=True, decor=False, source='DNSE'))
  File "/home/airflow/.local/lib/python3.9/site-packages/vnstock/technical.py", line 24, in stock_historical_data
    df = ohlc_data(symbol, start_date, end_date, resolution, type, headers=entrade_headers)
  File "/home/airflow/.local/lib/python3.9/site-packages/vnstock/technical.py", line 170, in ohlc_data
    response = requests.request("GET", url, headers=headers)
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1275, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1133, in read
    return self._sslobj.read(len, buffer)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-06-14T07:41:58.294+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=minio_upload_dag, task_id=crawl_data_task, execution_date=20240613T000000, start_date=20240614T073727, end_date=20240614T074158
[2024-06-14T07:41:58.328+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 41 for task crawl_data_task (Task received SIGTERM signal; 952)
[2024-06-14T07:41:58.380+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=952, status='terminated', exitcode=1, started='07:37:26') (952) terminated with exit code 1
[2024-06-14T07:41:58.384+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2024-06-14T07:41:58.421+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T07:57:14.169+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_upload_dag.crawl_data_task scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T07:57:14.177+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_upload_dag.crawl_data_task scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T07:57:14.177+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-14T07:57:14.186+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): crawl_data_task> on 2024-06-13 00:00:00+00:00
[2024-06-14T07:57:14.233+0000] {standard_task_runner.py:57} INFO - Started process 844 to run task
[2024-06-14T07:57:14.251+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'minio_upload_dag', 'crawl_data_task', 'scheduled__2024-06-13T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/Upload_minio.py', '--cfg-path', '/tmp/tmplfaoswm_']
[2024-06-14T07:57:14.254+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask crawl_data_task
[2024-06-14T07:57:14.345+0000] {task_command.py:415} INFO - Running <TaskInstance: minio_upload_dag.crawl_data_task scheduled__2024-06-13T00:00:00+00:00 [running]> on host 963b3fbfa4c9
[2024-06-14T07:57:14.441+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_upload_dag' AIRFLOW_CTX_TASK_ID='crawl_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T00:00:00+00:00'
[2024-06-14T08:02:30.377+0000] {logging_mixin.py:151} INFO - Time range is 165 days. Looping through 1 requests
[2024-06-14T08:02:31.355+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-06-14T08:02:31.567+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=minio_upload_dag, task_id=crawl_data_task, execution_date=20240613T000000, start_date=20240614T075714, end_date=20240614T080231
[2024-06-14T08:02:31.786+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-06-14T08:02:32.043+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-15T12:58:03.036+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_upload_dag.crawl_data_task scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-15T12:58:03.047+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_upload_dag.crawl_data_task scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-15T12:58:03.049+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-15T12:58:03.065+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): crawl_data_task> on 2024-06-13 00:00:00+00:00
[2024-06-15T12:58:03.080+0000] {standard_task_runner.py:57} INFO - Started process 1198 to run task
[2024-06-15T12:58:03.090+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'minio_upload_dag', 'crawl_data_task', 'scheduled__2024-06-13T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/Upload_minio.py', '--cfg-path', '/tmp/tmpu3ztcnxz']
[2024-06-15T12:58:03.097+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask crawl_data_task
[2024-06-15T12:58:03.187+0000] {task_command.py:415} INFO - Running <TaskInstance: minio_upload_dag.crawl_data_task scheduled__2024-06-13T00:00:00+00:00 [running]> on host 3d7c41a4db76
[2024-06-15T12:58:03.268+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_upload_dag' AIRFLOW_CTX_TASK_ID='crawl_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T00:00:00+00:00'
[2024-06-15T13:03:35.986+0000] {logging_mixin.py:151} INFO - Time range is 166 days. Looping through 1 requests
[2024-06-15T13:03:36.517+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-06-15T13:03:36.691+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=minio_upload_dag, task_id=crawl_data_task, execution_date=20240613T000000, start_date=20240615T125803, end_date=20240615T130336
[2024-06-15T13:03:36.825+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-06-15T13:03:37.007+0000] {taskinstance.py:2776} INFO - 2 downstream tasks scheduled from follow-on schedule check
